// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Brand struct {
	ID   int64
	Name string
}

type Category struct {
	ID   int64
	Slug string
}

type Provider struct {
	ID   int64
	Name string
}
