// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllBrands = `-- name: GetAllBrands :many
SELECT id, name
FROM brands
ORDER BY name
`

func (q *Queries) GetAllBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, getAllBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, slug
FROM categories
ORDER BY slug
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProviders = `-- name: GetAllProviders :many
SELECT id, name
FROM providers
ORDER BY name
`

func (q *Queries) GetAllProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, getAllProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForIndexing = `-- name: GetProductsForIndexing :many
SELECT
    p.id, p.name, p.price, p.currency, p.in_stock, p.image_url,
    p.canonical_product_url, p.created_at, p.updated_at,
    p.category_id, c.slug AS category_slug,
    p.provider_id, pr.name AS provider_name,
    p.brand_id, b.name AS brand_name
FROM products AS p
JOIN categories AS c ON c.id = p.category_id
JOIN providers AS pr ON pr.id = p.provider_id
LEFT JOIN brands AS b ON b.id = p.brand_id
WHERE p.id > $1
ORDER BY p.id ASC
LIMIT $2::integer
`

type GetProductsForIndexingParams struct {
	AfterID   int64
	BatchSize int32
}

type GetProductsForIndexingRow struct {
	ID                  int64
	Name                string
	Price               pgtype.Numeric
	Currency            string
	InStock             *bool
	ImageUrl            *string
	CanonicalProductUrl string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	CategoryID          int64
	CategorySlug        string
	ProviderID          int64
	ProviderName        string
	BrandID             *int64
	BrandName           *string
}

func (q *Queries) GetProductsForIndexing(ctx context.Context, arg GetProductsForIndexingParams) ([]GetProductsForIndexingRow, error) {
	rows, err := q.db.Query(ctx, getProductsForIndexing, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsForIndexingRow{}
	for rows.Next() {
		var i GetProductsForIndexingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Currency,
			&i.InStock,
			&i.ImageUrl,
			&i.CanonicalProductUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategorySlug,
			&i.ProviderID,
			&i.ProviderName,
			&i.BrandID,
			&i.BrandName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
